check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100

reporting:
  print: summary
  reports:
    - html
  dir: ./reports
  report-config:
    html:
      dir: coverage
